<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Avatar' => 'Аватар',
    'Base' => 'Главные',
    'Personal' => 'Персональные',
    'Activation Key' => 'Ключ активации',
    'Add User' => 'Создание нового пользователя',
    'Address' => 'Адрес',
    'Blocked' => 'Заблокирован',
    'City' => 'Город',
    'Confirm Password' => 'Подтверждение пароля',
    'Confirmed' => 'Подтверждён',
    'E-mail' => 'Почта',
    'First Name' => 'Имя',
    'Google Formatted Address' => 'Google адрес',
    'Last Name' => 'Фамилия',
    'Last Visit' => 'Последнее посещение',
    'Login' => 'Логин',
    'Name' => 'Полное имя',
    'Password' => 'Пароль',
    'Phone' => 'Телефон',
    'Profile' => 'Профиль',
    'Registered At' => 'Зарегистрирован',
    'Role' => 'Роль',
    'State' => 'Область',
    'Update User' => 'Обновление пользователя',
    'User ID' => 'ID Пользователя',
    'Users' => 'Пользователи',
    'Zip' => 'Индекс',
    'id' => 'Номер',
];
