<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure you want to delete this item?' => '',
    'Price ID' => '',
    'Product ID' => '',
    'SEO' => '',
    'Case' => 'Коробка',
    'Content' => 'Содержимое',
    'Cover' => 'Фото',
    'Created At' => 'Дата создания',
    'Created By' => 'Автор',
    'Delete' => 'Удалить',
    'Deleted' => 'Удален',
    'Description' => 'Описание',
    'Full Name' => 'Полное наименование',
    'Gram' => 'Грам',
    'ID' => 'Номер',
    'Images' => 'Изображения',
    'Kilogram' => 'Килограм',
    'Liter' => 'Литр',
    'Name' => 'Наименование',
    'New Product' => 'Новый товар',
    'Overview' => 'Основная информация',
    'Piece' => 'Штука',
    'Price' => 'Цена',
    'Products' => 'Товары',
    'Reset' => 'Сбросить',
    'Search' => 'Поиск',
    'Service' => 'Услуга',
    'Sku' => 'Артикул',
    'Unit' => 'Ед. изм.',
    'Update' => 'Обновить',
    'Updated At' => 'Дата обновления',
    'Updated By' => 'Обновлено',
];
