<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Account' => '',
    'Description' => '',
    'Email' => '',
    'Encryprion' => '',
    'Google Api' => '',
    'Host' => '',
    'Keywords' => '',
    'Maintenance Mode' => '',
    'Name' => '',
    'Password' => '',
    'Phone' => '',
    'Port' => '',
    'Username' => '',
    'Created' => 'Создал',
    'Created At' => 'Дата',
    'Created By' => 'Пользователь',
    'ID' => '№',
    'Model ID' => '№ записи',
    'Model Name' => 'Раздел',
    'Notifications' => 'Уведомления',
    'Text' => 'Текст',
    'Type' => 'Тип',
    'Updated' => 'Обновил',
    'has been created' => 'создан',
    'has been updated' => 'обновлен',
];
