<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Developer Settings' => '',
    'Email Settings' => '',
    'Font Size' => '',
    'ID' => '',
    'Overview' => '',
    'Search Engine Optimization' => '',
    'Google Api' => '@@Google API@@',
    'Maintenance Mode' => '@@Режим разработки@@',
    'Site Description' => '@@Описание сайта@@',
    'Site Email' => '@@E-mail сайта@@',
    'Site Font' => '@@Шрифт@@',
    'Site Font Size' => '@@Размер Шрифта@@',
    'Site Keywords' => '@@Ключевые слова@@',
    'Site Name' => '@@Название сайта@@',
    'Site Phone' => '@@Телефон@@',
    'Color' => 'Цвет',
    'Font' => 'Шрифт',
    'Language' => 'Язык',
    'Location' => 'Местоположение',
    'Navbar Color' => 'Цвет панели',
    'Site Settings' => 'Настройки сайта',
    'User ID' => '№ Пользователя',
];
