<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Disabled' => '',
    'ID' => '',
    'Lft' => '',
    'Lvl' => '',
    'Movable D' => '',
    'Movable L' => '',
    'Movable R' => '',
    'Movable U' => '',
    'Rgt' => '',
    'SEO' => '',
    'Url' => '',
    'Publish' => '@@Опубликовать@@',
    'Publish Date' => '@@Дата Публикации@@',
    'Search Engine Optimization' => '@@SEO@@',
    'Active' => 'Активна',
    'Collapsed' => 'Свернута',
    'Content' => 'Контент',
    'Created At' => 'Дата создания',
    'Created By' => 'Автор',
    'Description' => 'Описание',
    'Icon' => 'Иконка',
    'Icon Type' => 'Тип иконки',
    'Is Deleted' => 'Удален',
    'Keywords' => 'Ключевые слова',
    'Name' => 'Заголовок',
    'New Page' => 'Новая страница',
    'Overview' => 'Обзор',
    'Pages' => 'Страницы',
    'Readonly' => 'Только для чтения',
    'Removable' => 'Удалается',
    'Removable All' => 'Удялются страницы',
    'Root' => 'Главная',
    'Save' => 'Сохранить',
    'Selected' => 'Выбран',
    'Title' => 'Заголовок',
    'Updated At' => 'Обновлен',
    'Updated By' => 'Обновлен',
    'Visible' => 'Отобржается',
];
