<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Create Account' => 'Регистрация',
    'Email' => 'E-mail',
    'Email is incorrect' => 'E-mail указан неверно',
    'Have you forgot your password?' => 'Забыли пароль?',
    'Login is incorrect' => 'Имя пользователя указано неверно',
    'Password' => 'Пароль',
    'Password is incorrect' => 'Пароль указан неверно',
    'Please, confirm your email' => 'Пожалуйста, подтвердите свой E-mail',
    'Remember' => 'Запомнить меня',
    'Remember Me' => 'Запомнить меня',
    'Sign in' => 'Войти',
    'Sign up' => 'Регистрация',
    'Your account was blocked' => 'Ваш аккаунт заблокирован',
];
